jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Choose appropriate Java version
    steps:
      - checkout
      # Install Chrome and chromedriver
      - run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - run: wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo apt-get update && sudo apt-get install -y apt-transport-https
      - run: sudo apt-get update && sudo apt-get install -y software-properties-common
      - run: sudo add-apt-repository "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main"
      - run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - run: wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE
      - run: export LATEST_CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE)
      - run: wget https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
      - run: unzip chromedriver_linux64.zip -d /usr/local/bin
      # Run your build and test commands
      - run: mvn clean test
